CREATE TABLE OWNER
(
    ID            int          NOT NULL PRIMARY KEY AUTO_INCREMENT,
    NAME          varchar2(50) NOT NULL,
    EMAIL_ADDRESS varchar2(100),
    PHONE_NUMBER  varchar2(50)
);

CREATE TABLE PET
(
    ID int NOT NULL PRIMARY KEY AUTO_INCREMENT,
    OWNER_ID int NOT NULL,
    NAME varchar2(50) NOT NULL,
    CHIP_NO varchar2(50) NOT NULL,
    CONSTRAINT FK_Owner FOREIGN KEY (OWNER_ID) REFERENCES OWNER
);

CREATE TABLE QUARANTINE
(
    ID          int          NOT NULL PRIMARY KEY AUTO_INCREMENT,
    PET_ID      int          NOT NULL,
    TRACKING_NO varchar2(16) NOT NULL UNIQUE,
    CREATION    datetime     NOT NULL,
    ENDING      datetime,
    CONSTRAINT FK_Pet FOREIGN KEY (PET_ID) REFERENCES PET
);

CREATE TABLE STATE
(
    ID int NOT NULL PRIMARY KEY AUTO_INCREMENT,
    QUARANTINE_ID int NOT NULL,
    TYPE varchar2(50) NOT NULL,
    CREATION datetime NOT NULL,
    PAYLOAD_TEXT tinytext,
    PAYLOAD_DATETIME datetime,
    CONSTRAINT FK_Quarantine FOREIGN KEY (QUARANTINE_ID) REFERENCES QUARANTINE
);

CREATE TABLE ADMIN
(
    ID int NOT NULL PRIMARY KEY AUTO_INCREMENT,
    USERNAME varchar2(50) NOT NULL,
    PASSWORD varchar2(50) NOT NULL,
    ROLE varchar(20)
);