spring:
  datasource:
    url: jdbc:h2:file:./target/db
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  security:
    user:
      name: user
      password: p
  mail:
    host: smtp.gmail.com
    port: 587
    username: # PLACEHOLDER #
    password: # PLACEHOLDER'
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true